### ISSUE TITLE
Convert dae/obj to gltf Error

### ISSUE THREAD

**Issue by anilergin** [KhronosGroup/COLLADA2GLTF#53]
Hello,

1- Can I use kmz, kml for model? I tried but I couldn't see on map.

2- I am triying to convert over 1GB dae projects to gltf. but it couldn't complete succesfully. Converting broken always and always. It is sama with obj to gltf too. What can I do?

Thanks

**Comment by lasalvavida** [comment]
This project is strictly for converting COLLADA (.dae) files to glTF, so no kmz and kml are not supported. 

I really can't speak for conversion issues unless you can provide a model or a more specific description of your problem.

**Comment by anilergin** [comment]
**When I try to convert gltf from dae**
Firstly I get, WARNING: unsupported opaque mode:RGB_ZERO fallback to A_ONE

I changed RGB_ZERO's to A_ONE with notepad and tried again,

After 2 hours converting was continuing, but I checked the new file(.gltf), it was 0 byte.


**When I try to convert .obj I get this error**

<--- Last few GCs --->

  273647 ms: Mark-sweep 1369.0 (1435.0) -> 1358.0 (1435.0) MB, 1455.1 / 0.0 ms [allocation failure] [GC in old space requested].
  275289 ms: Mark-sweep 1358.0 (1435.0) -> 1358.0 (1435.0) MB, 1642.1 / 0.0 ms [allocation failure] [GC in old space requested].
  277037 ms: Mark-sweep 1358.0 (1435.0) -> 1364.6 (1405.0) MB, 1746.6 / 0.0 ms [last resort gc].
  278599 ms: Mark-sweep 1364.6 (1405.0) -> 1371.4 (1405.0) MB, 1561.9 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x15cf3d7cfb51 <JS Object>
    1: addFace(aka addFace) [/Users/MacBook/node_modules/obj2gltf/lib/loadObj.js:~198] [pc=0x37e1e557a5f5] (this=0x15cf3d704381 <undefined>,v1=0x88d52736eb9 <String[23]:  9293201/1512919/770561>,p1=0x88d52736ee1 <String[7]: 9293201>,u1=0x88d52736f01 <String[7]: 1512919>,n1=0x88d52736f21 <String[6]: 770561>,v2=0x88d52736f41 <String[23]:  9293200/1512920/770562>,p2=0x88d52736f69 <String[7]: 92932...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::HashTable<v8::internal::StringTable, v8::internal::StringTableShape, v8::internal::HashTableKey*>::EnsureCapacity(v8::internal::Handle<v8::internal::StringTable>, int, v8::internal::HashTableKey*, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::StringTable::LookupKey(v8::internal::Isolate*, v8::internal::HashTableKey*) [/usr/local/bin/node]
 7: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
 8: v8::internal::LookupIterator::LookupIterator(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::LookupIterator::Configuration) [/usr/local/bin/node]
 9: v8::internal::LookupIterator::PropertyOrElement(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, bool*, v8::internal::LookupIterator::Configuration) [/usr/local/bin/node]
10: v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
11: v8::internal::Runtime_KeyedGetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x37e1e4e092a7
13: 0x37e1e557a5f5
14: 0x37e1e5582184
15: 0x37e1e556f412
Abort trap: 6



I have about 70 model 1 gb in size per one. I have the project inside sketchedup. I can export da,obj,kml... So which format is better to convert to gltf? 

I am sharing also the two of that .dae models. 
https://wetransfer.com/downloads/a52a6a4dcfa4d7323abbf8f38ea283d820170531122018/8f4fa9b25315d3856e7ae32681bf819820170531122018/66d117


Thanks.

**Comment by anilergin** [comment]
I deleted almost everyting with skechup and now file is converted. But when I put to Cesium I got this error and model is not shown. Do you know what s problem?


RuntimeError: Failed to load buffer: http://localhost:8080/Apps/Sandcastle/images/333.bin
Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:43:19)
    at http://localhost:8080/Source/Scene/Model.js:1325:40
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:217:33)
    at http://localhost:8080/Source/ThirdParty/when.js:297:13
    at processQueue (http://localhost:8080/Source/ThirdParty/when.js:647:4)
    at _resolve (http://localhost:8080/Source/ThirdParty/when.js:333:4)
    at promiseReject (http://localhost:8080/Source/ThirdParty/when.js:366:11)
    at Promise.then (http://localhost:8080/Source/ThirdParty/when.js:217:33)
    at http://localhost:8080/Source/ThirdParty/when.js:298:7
    at processQueue (http://localhost:8080/Source/ThirdParty/when.js:647:4)

**Comment by pjcozzi** [comment]
> I have about 70 model 1 gb in size per one. 

@anilergin these files too large to load as individual glTFs.  We could try 3D Tiles (a spatial data structure built on glTF) if you are able to send me the source data.  For more details, see https://groups.google.com/forum/#!topic/cesium-dev/xLkYIuku9hA

**Comment by lexaknyazev** [comment]
@pjcozzi 
> these files too large to load as individual glTFs

COLLADA files could be _very_ big for different reasons.
I don't see any substantial problem when binary buffer is huge but glTF itself isn't.

**Comment by pjcozzi** [comment]
I don't think I would load 70 1 GB (or whatever smaller size it ends up being) glTF models at once in Cesium, that is why we made 3D Tiles. 😄 

@lasalvavida if you have bandwidth to evaluate COLLADA2GLTF for this particular issue, please go for it!

**Comment by lasalvavida** [comment]
Closing due to inactivity; the model link no longer being valid.

I am interested in how the new converter performs vs. the old one with large models, so @anilergin if you want to re-upload the model, I'm happy to take a look at it.
